// utils/constants.js


export const initialLeaveRequests = [
  {
    id: 1,
    employee: 'John Doe',
    employeeId: 'EMP001',
    avatar: 'https://randomuser.me/api/portraits/men/32.jpg',
    group: 'dev',
    type: 'Vacation',
    dates: ['2024-06-15', '2024-06-18'],
    duration: 4,
    status: 'pending',
    reason: 'Family vacation to Hawaii. Need time off for family trip.',
    submitted: '2024-06-10 09:30',
    approver: 'Sarah Johnson (Lead)',
    priority: 'high',
    conversation: [],
    attachments: [],
    notes: 'Employee has remaining leaves: 12 days',
    rating: 4.5
  },
  {
    id: 2,
    employee: 'Jane Smith',
    employeeId: 'EMP002',
    avatar: 'https://randomuser.me/api/portraits/women/68.jpg',
    group: 'design',
    type: 'Sick Leave',
    dates: ['2024-06-20', '2024-06-20'],
    duration: 1,
    status: 'approved',
    reason: 'Medical appointment with specialist doctor.',
    submitted: '2024-06-12 14:20',
    approver: 'Emma Wilson (Lead)',
    priority: 'medium',
    conversation: [],
    attachments: [],
    notes: 'Regular medical checkup',
    rating: 5
  },
  {
    id: 3,
    employee: 'Alex Johnson',
    employeeId: 'EMP003',
    avatar: 'https://randomuser.me/api/portraits/men/67.jpg',
    group: 'qa',
    type: 'Personal',
    dates: ['2024-07-01', '2024-07-03'],
    duration: 3,
    status: 'pending',
    reason: 'Family event - wedding',
    submitted: '2024-06-25 10:15',
    approver: 'Robert Brown (Lead)',
    priority: 'medium',
    conversation: [],
    attachments: [],
    notes: '',
    rating: 0
  },
  {
    id: 4,
    employee: 'Sarah Miller',
    employeeId: 'EMP004',
    avatar: 'https://randomuser.me/api/portraits/women/26.jpg',
    group: 'hr',
    type: 'Vacation',
    dates: ['2024-07-10', '2024-07-20'],
    duration: 10,
    status: 'approved',
    reason: 'Summer vacation with family',
    submitted: '2024-06-28 14:45',
    approver: 'Lisa Taylor (HR Head)',
    priority: 'low',
    conversation: [],
    attachments: [],
    notes: 'Long planned vacation',
    rating: 4.2
  }
];